version: '3'

networks:
  tokdeck-prod:

services:
  tokdeck-mysql-prod:
    build: tokdeck-mysql
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
     - ./tokdeck-mysql/conf/conf.d-prod:/etc/mysql/conf.d
     - /var/tokdeck-mysql:/var/lib/mysql
    networks:
      tokdeck-prod:

  tokdeck-rabbitmq-prod:
    build: tokdeck-rabbitmq
    tty: true
    networks:
      tokdeck-prod:
    volumes:
      - /var/tokdeck-rabbitmq:/var/lib/rabbitmq

  tokdeck-nginx-prod:
    build: tokdeck-nginx
    tty: true
    depends_on:
     - tokdeck-runner-prod
    volumes:
     - ./tokdeck-nginx/conf/init-prod.sh:/root/host/init.sh
     - ./tokdeck-nginx/conf/nginx-prod.conf:/etc/nginx/nginx.conf
     - /etc/ssl/certs/tokdeck:/etc/nginx/ssl
     - ..:/var/www/tokdeck
    ports:
     - "7676:80"
    networks:
      tokdeck-prod:

  tokdeck-runner-prod:
    build: tokdeck-runner
    tty: true
    depends_on:
     - tokdeck-mysql-prod
     - tokdeck-rabbitmq-prod
    env_file:
     - ./tokdeck-runner/conf/prod.env
    volumes:
     - ./tokdeck-runner/conf/init-prod.sh:/root/host/init.sh
     - ..:/var/www/tokdeck
     - ./tokdeck-runner/conf/ecosystem.config-prod.js:/var/www/tokdeck/ecosystem.config.js
    networks:
      tokdeck-prod:
