version: '3'

networks:
  tokdeck-prod:

services:
  tokdeck-mysql-prod:
    build: tokdeck-mysql
    tty: true
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
     - ./tokdeck-mysql/conf/conf.d-prod:/etc/mysql/conf.d
     - ./tokdeck-mysql/conf/mysql.conf.d-prod:/etc/mysql/mysql.conf.d
     - /var/tockdeck-mysql:/var/lib/mysql
    networks:
      tokdeck-prod:

  tokdeck-rabbitmq-prod:
    build: tokdeck-rabbitmq
    tty: true
    networks:
      tokdeck-prod:
    volumes:
      - /var/tockdeck-rabbitmq:/var/lib/rabbitmq

  tokdeck-nginx-prod:
    build: tokdeck-nginx
    tty: true
    depends_on:
     - tokdeck-runner-prod
    volumes:
     - ./tokdeck-nginx/conf/init-prod.sh:/root/host/init.sh
     - ./tokdeck-nginx/conf/nginx-prod.conf:/etc/nginx/nginx.conf
     - ../ssl:/etc/nginx/ssl
    ports:
     - "7676:80"
    networks:
      tokdeck-prod:
        aliases:
          - tokdeck.kalaus.ru
          - a.cdn.tokdeck.kalaus.ru
          - b.cdn.tokdeck.kalaus.ru
          - c.cdn.tokdeck.kalaus.ru
          - d.cdn.tokdeck.kalaus.ru

  tokdeck-runner-prod:
    build: tokdeck-runner
    tty: true
    depends_on:
     - tokdeck-mysql-prod
     - tokdeck-rabbitmq-prod
    env_file:
     - ./tokdeck-runner/conf/prod.env
    volumes:
     - ./tokdeck-runner/conf/init-prod.sh:/root/host/init.sh
     - ..:/var/www/tokdeck
    networks:
      tokdeck-prod:
