FROM tokdeck-node:latest

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y software-properties-common
RUN apt-get install -y dirmngr
RUN apt-get install -y build-essential
RUN apt-get install -y git-core
